### ISSUE TITLE
No provider for InjectionToken ng-gapi.config!

### ISSUE THREAD

**Issue by AndyBrownlie** [rubenCodeforges/iService#8]
Hey Ruben

I'm getting the error above when executing a unit test using angular-cli with jasmine/karma.
The test in particular is trying to instantiate the service into which I inject the GoogleApiService.

I have configured the appropriate module as per your readme example.

thanks in advance

**Comment by rubenCodeforges** [comment]
@AndyBrownlie hi , i think its just the test , doesnt relates to the ng-gapi itself.
In any case i can help you out with the test, just paste here the code of the test.

**Comment by rubenCodeforges** [comment]
@AndyBrownlie btw , this is not the right place for the issue , please move to the correct repository https://github.com/rubenCodeforges/ng-gapi/issues

**Comment by AndyBrownlie** [comment]
done: https://github.com/rubenCodeforges/ng-gapi/issues/27
